# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-DBUnit
version:      0.04
version_from: lib/Test/DBUnit.pm
installdirs:  site
license: perl
requires:
    Abstract::Meta::Class:                    0
    DBIx::Connection:                         0
    Simple::SAX::Serializer:                  0
    Test::Pod                                 0
    Test::Pod::Coverage                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
