name:         Test-DBUnit
version:      0.05
author:
  - 'Adrian Witas <adrian@webapp.strefa.pl>'
abstract: Database test framework
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
    Abstract::Meta::Class:                    0
    DBIx::Connection:                         0
    Simple::SAX::Serializer:                  0
build_requires:
    Test::Pod:                                0
    Test::Pod::Coverage:                      0

provides:
DBUnit:
  file: lib/DBUnit.pm
Test::DBUnit:
  file: lib/Test/DBUnit.pm
version_from: lib/Test/DBUnit.pm
installdirs:  site
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2

