--- #YAML:1.0
name:                Test-DBUnit
version:             0.20
abstract:            Database test framework
license:             perl
author:              'Adrian Witas <adrian@webapp.strefa.pl>'
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Abstract::Meta::Class:         0
    Data::Dumper:                  0
    DBIx::Connection:              0.13
    IO::File:                      0
    Simple::SAX::Serializer:       0.05
    Sub::Uplevel:                  0
    Test::Builder:                 0
    Test::Pod:                     0
    Test::Pod::Coverage:           0
    XML::SAX:                      0
    XML::Writer:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
