--- #YAML:1.0
name:                Test-DBUnit
version:             0.12
author:
  - 'Adrian Witas <adrian@webapp.strefa.pl>'
abstract: Database test framework
license: perl
resources:
  license: http://dev.perl.org/licenses/
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:
    perl:                          5.6.1
    Abstract::Meta::Class:         0
    DBIx::Connection:              0.08
    XML::SAX:			   0
    Simple::SAX::Serializer:       0
    Sub::Uplevel:                  0
    Test::Builder:                 0
    Test::Pod:                     0
    Test::Pod::Coverage:           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
